package com.portfolioos.core.llm;

import com.portfolioos.core.persistence.DuckDbProjector;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class SqlGeneratorService {

    private final ChatClient.Builder chatClientBuilder;
    private final DuckDbProjector duckDbProjector;

    private static final String SCHEMA_PROMPT = """
        You are an expert DuckDB SQL developer for a financial portfolio database.
        The database contains two projected analytical tables:

        1. projected_events (
            id VARCHAR PRIMARY KEY,
            asset_id VARCHAR NOT NULL,
            asset_name VARCHAR NOT NULL,
            isin VARCHAR,
            event_type VARCHAR NOT NULL, -- 'ACQUISITION', 'DISPOSAL', 'SIP_INSTALMENT', 'BONUS', 'SPLIT'
            event_date VARCHAR NOT NULL, -- YYYY-MM-DD
            units VARCHAR NOT NULL,
            price_per_unit VARCHAR NOT NULL,
            gross_amount VARCHAR NOT NULL,
            source_document_id VARCHAR NOT NULL,
            ingested_at VARCHAR NOT NULL
        )

        2. nav_history (
            asset_id VARCHAR NOT NULL,
            nav_date VARCHAR NOT NULL, -- YYYY-MM-DD
            nav DOUBLE NOT NULL,
            PRIMARY KEY (asset_id, nav_date)
        )

        CRITICAL INSTRUCTIONS:
        - Output ONLY valid, executable DuckDB SQL.
        - The query MUST be a read-only SELECT statement.
        - Do NOT include any markdown formatting, code block fences (```), explanations, or trailing comments.
        """;

    public SqlGeneratorService(ChatClient.Builder chatClientBuilder, DuckDbProjector duckDbProjector) {
        this.chatClientBuilder = chatClientBuilder;
        this.duckDbProjector = duckDbProjector;
    }

    public record SqlQueryResult(
        String generatedSql,
        List<Map<String, Object>> data,
        String status,
        String errorMessage
    ) {}

    public SqlQueryResult generateAndExecute(String userPrompt) {
        try {
            ChatClient chatClient = chatClientBuilder.build();
            String rawSql = chatClient.prompt()
                .system(SCHEMA_PROMPT)
                .user(userPrompt)
                .call()
                .content();

            if (rawSql == null || rawSql.isBlank()) {
                return new SqlQueryResult("", Collections.emptyList(), "ERROR", "Empty SQL generated by LLM");
            }

            // Clean markdown syntax if present
            String sql = rawSql.replaceAll("```sql", "").replaceAll("```", "").trim();

            validateAndSanitizeSql(sql);

            List<Map<String, Object>> results = executeDuckDbQuery(sql);
            return new SqlQueryResult(sql, results, "SUCCESS", null);
        } catch (Exception e) {
            return new SqlQueryResult("", Collections.emptyList(), "ERROR", e.getMessage());
        }
    }

    private void validateAndSanitizeSql(String sql) {
        String upper = sql.toUpperCase();

        // 1. Strict SELECT / WITH prefix check
        if (!upper.startsWith("SELECT") && !upper.startsWith("WITH")) {
            throw new SecurityException("Security violation: Only read-only SELECT or WITH queries are permitted.");
        }

        // 2. Prevent multi-statement execution
        if (sql.contains(";") && sql.indexOf(";") != sql.length() - 1) {
            throw new SecurityException("Security violation: Multi-statement queries are forbidden.");
        }

        // 3. Block file read/write, system, and administrative DuckDB table functions
        String[] forbiddenTokens = {
            "READ_CSV", "READ_CSV_AUTO", "READ_PARQUET", "READ_JSON", "READ_NDJSON",
            "READ_TEXT", "ST_READ", "GLOB", "READ_BLOB", "READ_FILE", "WRITE_CSV",
            "COPY", "EXPORT", "INSTALL", "LOAD", "PRAGMA", "ATTACH", "DETACH", "QUERY_TABLE"
        };

        for (String token : forbiddenTokens) {
            if (upper.matches(".*\\b" + token + "\\b.*")) {
                throw new SecurityException("Security violation: Restricted function call '" + token + "' detected.");
            }
        }
    }

    private List<Map<String, Object>> executeDuckDbQuery(String sql) {
        List<Map<String, Object>> rows = new ArrayList<>();
        String dbPath = new java.io.File("data/tax_ledger.duckdb").getAbsolutePath();
        String jdbcUrl = "jdbc:duckdb:" + dbPath + "?access_mode=READ_ONLY";

        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(jdbcUrl);
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(sql)) {

            java.sql.ResultSetMetaData meta = rs.getMetaData();
            int colCount = meta.getColumnCount();

            while (rs.next()) {
                Map<String, Object> row = new LinkedHashMap<>();
                for (int i = 1; i <= colCount; i++) {
                    row.put(meta.getColumnLabel(i), rs.getObject(i));
                }
                rows.add(row);
            }
        } catch (Exception e) {
            throw new RuntimeException("DuckDB SQL execution error: " + e.getMessage(), e);
        }
        return rows;
    }
}
