package com.portfolioos.core.tax;

import com.portfolioos.core.model.AssetCategory;
import com.portfolioos.core.model.Lot;
import com.portfolioos.core.model.MatchedLot;
import com.portfolioos.core.model.TaxEvent;
import com.portfolioos.core.model.TaxTerm;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;

public class ScheduleCgExporter {

    public static String generateCsvReport(List<MatchedLot> matchedLots, String fiscalYear) {
        StringBuilder csv = new StringBuilder();
        csv.append("ITR SCHEDULE CG - CAPITAL GAINS SUMMARY (FY ").append(fiscalYear).append(")\n");
        csv.append("Generated by Portfolio OS Tax Engine\n\n");
        csv.append("ISIN,Scheme Name,Purchase Date,Sale Date,Holding Days,Units Sold,Purchase Cost (INR),Sale Value (INR),Capital Gain (INR),Tax Classification,Section,Tax Rate\n");

        BigDecimal totalLtcgEquity = BigDecimal.ZERO;
        BigDecimal totalStcgEquity = BigDecimal.ZERO;
        BigDecimal totalDebtGain = BigDecimal.ZERO;

        for (MatchedLot match : matchedLots) {
            Lot buy = match.buyLot();
            TaxEvent sell = match.sellEvent();

            long days = ChronoUnit.DAYS.between(buy.acquisitionDate(), sell.eventDate());
            AssetCategory category = TaxClassifier.detectCategory(buy.assetId(), buy.assetName());
            boolean isListed = TaxClassifier.isListed(buy.assetId(), buy.assetName());
            TaxTerm term = TaxClassifier.classifyTaxTerm(category, days, fiscalYear, isListed);

            BigDecimal units = match.matchedUnits();
            BigDecimal cost = buy.pricePerUnit().multiply(units).setScale(2, RoundingMode.HALF_UP);
            BigDecimal saleVal = sell.pricePerUnit().multiply(units).setScale(2, RoundingMode.HALF_UP);
            BigDecimal gain = saleVal.subtract(cost);

            String section;
            String taxRate;

            if (category == AssetCategory.EQUITY || category == AssetCategory.EQUITY_ORIENTED) {
                if (term == TaxTerm.LONG_TERM) {
                    section = "112A";
                    taxRate = "12.5%";
                    totalLtcgEquity = totalLtcgEquity.add(gain);
                } else {
                    section = "111A";
                    taxRate = "20.0%";
                    totalStcgEquity = totalStcgEquity.add(gain);
                }
            } else {
                section = "50AA";
                taxRate = "Slab Rate";
                totalDebtGain = totalDebtGain.add(gain);
            }

            csv.append(escapeCsv(buy.assetId())).append(",")
               .append(escapeCsv(buy.assetName())).append(",")
               .append(buy.acquisitionDate()).append(",")
               .append(sell.eventDate()).append(",")
               .append(days).append(",")
               .append(units.toPlainString()).append(",")
               .append(cost.toPlainString()).append(",")
               .append(saleVal.toPlainString()).append(",")
               .append(gain.toPlainString()).append(",")
               .append(term.name()).append(",")
               .append(section).append(",")
               .append(taxRate).append("\n");
        }

        csv.append("\nSUMMARY TAX OBLIGATION RECAP\n");
        csv.append("Equity Sec 112A Total LTCG Gain: INR ").append(totalLtcgEquity.toPlainString()).append("\n");
        csv.append("Sec 112A Annual Exemption Limit: INR 125000.00\n");
        BigDecimal taxableLtcg = totalLtcgEquity.subtract(new BigDecimal("125000.00")).max(BigDecimal.ZERO);
        csv.append("Net Taxable Sec 112A LTCG: INR ").append(taxableLtcg.toPlainString()).append("\n");
        csv.append("Equity Sec 111A Total STCG Gain (20%): INR ").append(totalStcgEquity.toPlainString()).append("\n");
        csv.append("Debt Sec 50AA Total Gain (Slab Rate): INR ").append(totalDebtGain.toPlainString()).append("\n");

        return csv.toString();
    }

    private static String escapeCsv(String text) {
        if (text == null) return "";
        if (text.contains(",") || text.contains("\"") || text.contains("\n")) {
            return "\"" + text.replace("\"", "\"\"") + "\"";
        }
        return text;
    }
}
