package com.portfolioos.core.tax;

import com.portfolioos.core.matcher.TaxClassifier;
import com.portfolioos.core.model.AssetCategory;
import com.portfolioos.core.model.MatchedLot;
import com.portfolioos.core.model.TaxTerm;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

public class ScheduleCgExporter {

    public static String generateCsvReport(List<MatchedLot> matchedLots, String fiscalYear) {
        StringBuilder csv = new StringBuilder();
        csv.append("ITR SCHEDULE CG - CAPITAL GAINS SUMMARY (FY ").append(fiscalYear).append(")\n");
        csv.append("Generated by Portfolio OS Tax Engine\n\n");
        csv.append("ISIN,Purchase Date,Sale Date,Holding Days,Units Sold,Purchase Cost (INR),Sale Value (INR),Capital Gain (INR),Tax Classification,Section,Tax Rate\n");

        BigDecimal totalLtcgEquity = BigDecimal.ZERO;
        BigDecimal totalStcgEquity = BigDecimal.ZERO;
        BigDecimal totalDebtGain = BigDecimal.ZERO;

        for (MatchedLot match : matchedLots) {
            long days = match.holdingPeriodDays();
            AssetCategory category = match.assetCategory();
            TaxTerm term = match.taxTerm();

            BigDecimal units = match.unitsMatched();
            BigDecimal cost = match.costBasis().setScale(2, RoundingMode.HALF_UP);
            BigDecimal saleVal = match.saleProceeds().setScale(2, RoundingMode.HALF_UP);
            BigDecimal gain = match.realizedGain().setScale(2, RoundingMode.HALF_UP);

            String section;
            String taxRate;

            if (category == AssetCategory.EQUITY) {
                if (term == TaxTerm.LONG_TERM) {
                    section = "112A";
                    taxRate = "12.5%";
                    totalLtcgEquity = totalLtcgEquity.add(gain);
                } else {
                    section = "111A";
                    taxRate = "20.0%";
                    totalStcgEquity = totalStcgEquity.add(gain);
                }
            } else {
                section = "50AA";
                taxRate = "Slab Rate";
                totalDebtGain = totalDebtGain.add(gain);
            }

            csv.append(escapeCsv(match.assetId())).append(",")
               .append(match.acquisitionDate()).append(",")
               .append(match.disposalDate()).append(",")
               .append(days).append(",")
               .append(units.toPlainString()).append(",")
               .append(cost.toPlainString()).append(",")
               .append(saleVal.toPlainString()).append(",")
               .append(gain.toPlainString()).append(",")
               .append(term.name()).append(",")
               .append(section).append(",")
               .append(taxRate).append("\n");
        }

        csv.append("\nSUMMARY TAX OBLIGATION RECAP\n");
        csv.append("Equity Sec 112A Total LTCG Gain: INR ").append(totalLtcgEquity.toPlainString()).append("\n");
        csv.append("Sec 112A Annual Exemption Limit: INR 125000.00\n");
        BigDecimal taxableLtcg = totalLtcgEquity.subtract(new BigDecimal("125000.00")).max(BigDecimal.ZERO);
        csv.append("Net Taxable Sec 112A LTCG: INR ").append(taxableLtcg.toPlainString()).append("\n");
        csv.append("Equity Sec 111A Total STCG Gain (20%): INR ").append(totalStcgEquity.toPlainString()).append("\n");
        csv.append("Debt Sec 50AA Total Gain (Slab Rate): INR ").append(totalDebtGain.toPlainString()).append("\n");

        return csv.toString();
    }

    private static String escapeCsv(String text) {
        if (text == null) return "";
        if (text.contains(",") || text.contains("\"") || text.contains("\n")) {
            return "\"" + text.replace("\"", "\"\"") + "\"";
        }
        return text;
    }
}
