server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: portfolio-os-core
  threads:
    virtual:
      enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    com.portfolioos.core: DEBUG
    org.springframework.web: INFO
